stages:
    - build
    - deploy
    - clear

build docker image:
    image: docker:20.10.5
    services:
        - docker:20.10.5-dind
    stage: build
    variables:
        #DOCKER_HOST: tcp://docker:2376
        #DOCKER_TLS_CERTDIR: "/certs"
        IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH"
    before_script:
        - docker login --username="$CI_REGISTRY_USER" --password="$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
        - docker pull "$IMAGE" || true
    script:
        - >-
            docker build
            --tag "$IMAGE"
            .
        - docker push "$IMAGE"
    tags:
        - ufsm-pnip



deploy docker image:
    stage: deploy
    variables:
        SERVICE_REQUESTED: API
        COMMAND: deploy
        IMAGE_REGISTER: $CI_REGISTRY_IMAGE
        BRANCH_NAME: $CI_COMMIT_BRANCH
    trigger:
        project: br.ufsm.lumac1/pnip-mpa/infra/review-env-deployer
        branch: main

clear docker:
    image: docker:20.10.5
    stage: clear
    variables:
        SOURCE_BRANCH: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    script:
        - ls
    only:
        refs:
            - merge_requests
        variables:
            - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
